/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <BitMath.h>
#include <std_typo.h>
#include <rcc_int.h>
#include <GPIO_interface.h>
#include <LCD.h>
#include "NVIC.h"
#include "ISR_Interrupts.h"
#include "SYSTICK.h"
#include "delay.h"
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

extern counter;

void toggle_led(u8 val);

int main(void)
{
	/* Loop forever */
	MRCC_voidInit();
	MRCC_enumSetPeripheralClock(APB2, GPIOA , RCC_ENABLE );
	MRCC_enumSetPeripheralClock(APB2, GPIOB , RCC_ENABLE );
	SYSTICK_Init();
	SYSTICK_SetCallback(toggle_led);
	SYSTICK_SetTime(1, HSI_CLOCK);
	SYSTICK_Start();
	LCD_Init();

	while(1){
	    if(counter == 1){
	    	LCD_clear();
	    }
	    else if(counter == 5){
			uint8 str[] = {'G', '6'};
			LCD_SendString1(0, 0, 2, str);
		}
		else if(counter == 6){
			LCD_clear();
		}
		else if(counter == 10){
			uint8 str1[] = {'G', '6'};
			LCD_SendString1(0, 0, 2, str1);

			uint8 str2[] = {'F', 'R', 'E', 'E', ' ', 'P', 'A', 'L', 'E', 'S', 'T', 'I', 'N', 'E'};
			LCD_SendString1(2, 0, 16, str2);
			counter = 0;
		}
	}
}

void nested_int(){
	MRCC_voidInit();
		MRCC_enumSetPeripheralClock(APB2, GPIOA , RCC_ENABLE );
		MRCC_enumSetPeripheralClock(APB2, GPIOB , RCC_ENABLE );
		MRCC_enumSetPeripheralClock(APB1, WWDG_PIN , RCC_ENABLE );
		MRCC_enumSetPeripheralClock(APB2, ADC3EN_PIN , RCC_ENABLE );

		LCD_Init();

		DNVIC_SetPriorityGrouping(TWO_PREEMPTION_TWO_SUBGROUP);

		DNVIC_EnableIRQ(WWDG);
		DNVIC_EnableIRQ(ADC3);
		u8 subgroub = 0b1110;

		DNVIC_SetPriority(WWDG, subgroub);
		DNVIC_SetPriority(ADC3, 0);

		DNVIC_SetPendingIRQ(WWDG);
}

void toggle_led(u8 val){
	DIO_voidSetPinDirection(PORTA, PIN7, GPIO_OUTPUT_10MHZ_PP);
	DIO_voidSetPinValue(PORTA, PIN7, val);
}
